import { BsPeopleCircle as icon } from 'react-icons/bs';
import Link from '../../src/link';
import React from 'react';

export default {
  title: 'Client',
  name: 'client',
  type: 'document',
  icon,
  fields: [
    {
      title: 'Active',
      name: 'isActive',
      type: 'boolean',
      description: `Is this person an active client?`,
      validation: (Rule) => Rule.required(),
    },
    {
      title: 'First Name',
      name: 'firstName',
      type: 'string',
      validation: (Rule) => Rule.required().min(2).warning('First names should be longer than 2 characters'),
    },
    {
      title: 'Second Name',
      name: 'secondName',
      type: 'string',
      validation: (Rule) => Rule.required().min(2).warning('Second names should be longer than 2 characters'),
    },
    {
      title: 'Age',
      name: 'age',
      type: 'number',
    },
    {
      title: 'UUID',
      name: 'uuid',
      type: 'string',
      description: `This is generated by the signup process on Google Firebase. For now, we need to create a new user there then paste the generated UUID here.`
    },
    {
      name: 'link',
      title: 'Link',
      type: 'string',
      inputComponent: Link,
    },
    {
      title: 'Avitar',
      name: 'avitar',
      type: 'image',
      description: `Put an image of the person here. This will appear on their profile screen on the app.`,
      options: {
        hotspot: true, // Make the image editable
      },
    },
    {
      title: 'Notes',
      name: 'notes',
      type: 'array',
      of: [{ type: 'block' }],
      description: ``,
      validation: (Rule) => Rule.min(10).warning('Notes should be longer than 50 characters'),
    },

    {
      title: 'Assigned Workouts',
      name: 'workout',
      type: 'array',
      of: [
        {
          type: 'reference',
          to: [{ type: "workout" }
          ]
        }
      ]
    }
  ],
  preview: {
    select: {
      title: 'firstName',
      subtitle: 'secondName',
      media: 'avitar',
    },
  },
  initialValue: {
    isActive: true,
  },
};
